<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp-Message</name>
   <tag></tag>
   <elementGuidId>7aa0dc58-8a89-4ca9-953f-63981ec0f540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.message</value>
   </webElementProperties>
</WebElementEntity>
