<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Denied-CC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e622653f-41bb-4ba0-904b-4cfdea8b118d</testSuiteGuid>
   <testCaseLink>
      <guid>0f7b1838-fcd7-4464-97de-eb5ecc822b21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/01-Navigate Url</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1fa3b0e0-56c1-4bcd-bb0e-27abfd8f7bda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/02-Shopping Cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1515af3f-fe85-495e-9631-128e78685e7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5279a8cb-300d-488c-984f-66b04ffa6622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c202129-1d9f-4764-9a38-aec6e4cece57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f569efdc-8bdb-490e-b2f3-63372f77a024</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a73f1667-6872-4d29-a1f6-823b60c8d45c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b22c0cc9-8b57-40c5-bd7e-7343d6d888fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4543651d-8412-424e-b2a3-20630e925a1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef0af920-1e25-4815-9d54-1de4806ad7c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>694c14d5-8a94-454e-9ae7-ff9db1870dd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e0951be-f807-4624-9582-f43f9996b72d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aa9cd66-88f8-46d9-8eca-28b97f5b4719</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5668ddba-d369-43f9-b483-bbfec68ea6d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>792d3806-99d3-46fc-aa7e-cf499eb0b309</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f57d7e3b-8c97-425c-95f2-9cf9b13be003</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/03-Order Summary</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>93e866f1-47a0-400a-8342-35c184e7e2e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/04-SelectPayment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5ab27d3d-f2c6-4426-b167-49bd62a3a676</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/05-PayNow-Denied-CC</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3b57efa-30e3-4977-9ff3-9e3cf97290ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b6affc5-814e-47e4-986d-cd27e167e0ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/06-Issuing Bank - Denied-CC</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>59fc3a8d-85eb-4970-a05b-03ffdd7875ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/09-Close Browser</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
