<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Succes-CC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f4aaa483-52de-4b83-ac60-20d95ff91ebf</testSuiteGuid>
   <testCaseLink>
      <guid>33422835-ae04-4c06-b414-1e18fe997099</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/01-Navigate Url</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bc2043a7-f796-43a9-8b8a-b00dc2319eaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/02-Shopping Cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1515af3f-fe85-495e-9631-128e78685e7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5279a8cb-300d-488c-984f-66b04ffa6622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c202129-1d9f-4764-9a38-aec6e4cece57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f569efdc-8bdb-490e-b2f3-63372f77a024</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a73f1667-6872-4d29-a1f6-823b60c8d45c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b22c0cc9-8b57-40c5-bd7e-7343d6d888fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4543651d-8412-424e-b2a3-20630e925a1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef0af920-1e25-4815-9d54-1de4806ad7c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>694c14d5-8a94-454e-9ae7-ff9db1870dd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e0951be-f807-4624-9582-f43f9996b72d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aa9cd66-88f8-46d9-8eca-28b97f5b4719</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5668ddba-d369-43f9-b483-bbfec68ea6d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>792d3806-99d3-46fc-aa7e-cf499eb0b309</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bd4b3c6-5d87-4d57-b6f4-bf5802b2ec00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Midtrans/02-Shopping Cart - Empty Data</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ad54e57d-12a9-422f-b996-00678b8a0122</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/03-Order Summary</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>22672f66-7418-4ddf-90e8-b7c99f755cd8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/04-SelectPayment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>42414df0-e747-442d-ad54-937a3be0eb4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Midtrans/05-PayNow-Negative</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5c9db6d7-9c93-47f1-8760-7ec164c9d5ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/05-PayNow</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bdb80edd-9417-480d-a9f4-0ffced896a89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/06-Issuing Bank</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>00f7b25a-93aa-4168-8a4c-6524e95ead2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans/09-Close Browser</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
