<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-continue-os</name>
   <tag></tag>
   <elementGuidId>e663d00b-c8d2-4152-b7da-e62550e56938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.button-main-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.button-main-content</value>
   </webElementProperties>
</WebElementEntity>
