<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-ts-done</name>
   <tag></tag>
   <elementGuidId>13412483-c122-4491-8490-9999ce690519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.button-main-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.button-main-content</value>
   </webElementProperties>
</WebElementEntity>
