<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl-verify-body-title</name>
   <tag></tag>
   <elementGuidId>91c4b056-daa3-46ad-a667-46802447f3de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[.='Name'][count(. | //*[@class = 'text-body-title' and (text() = 'Name' or . = 'Name')]) = count(//*[@class = 'text-body-title' and (text() = 'Name' or . = 'Name')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-body-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[.='Name']</value>
   </webElementProperties>
</WebElementEntity>
