<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl-transaction-success</name>
   <tag></tag>
   <elementGuidId>e80a85b6-8f15-4d00-93bc-1682b778a8b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.text-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.text-bold</value>
   </webElementProperties>
</WebElementEntity>
