<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl-iframe-issuing-bank</name>
   <tag></tag>
   <elementGuidId>08bc1f9f-1994-4658-9d52-e6ea7e5f1d37</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;application&quot;]/div[3]/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@style = 'width: 100%; height: 100%; border: 0px; position: absolute; left: 0px; top: 0px;']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>width: 100%; height: 100%; border: 0px; position: absolute; left: 0px; top: 0px;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
</WebElementEntity>
