<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_verifyPrice</name>
   <tag></tag>
   <elementGuidId>3f21519a-7474-4338-bd15-d170732027d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.price</value>
   </webElementProperties>
</WebElementEntity>
