<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_verifyQty</name>
   <tag></tag>
   <elementGuidId>c9bc7d38-590c-4331-b5e9-4f9aa4df9582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
</WebElementEntity>
