<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_inputAddress</name>
   <tag></tag>
   <elementGuidId>aac10a7a-615c-434b-bf01-256e9a094331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
</WebElementEntity>
