<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_verifyProduct</name>
   <tag></tag>
   <elementGuidId>d74b5599-c839-454d-a469-6c3d51eca783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
</WebElementEntity>
