<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PIM</name>
   <tag></tag>
   <elementGuidId>89a74fce-d436-4395-9745-d174f2b25099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//b[.='PIM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//b[.='PIM']</value>
   </webElementProperties>
</WebElementEntity>
