<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_errormessage</name>
   <tag></tag>
   <elementGuidId>c9a28af5-c3fc-44ff-aa7f-dfb72862f46a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.error</value>
   </webElementProperties>
</WebElementEntity>
